.\"
.\" Copyright (c) 2009 Matt Jibson <matt.jibson@gmail.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd April 22 2009
.Dt BI 1
.Os
.Sh NAME
.Nm bi
.Nd audio file resampling tool
.Sh SYNOPSIS
.Nm bi
.Ar input rate output
.Sh DESCRIPTION
The
.Nm
tool resamples the audio file
.Ar input
to
.Ar rate
Hz and saves the result to
.Ar output .
Input files must be in a format readable by libsndfile.
.Sh EXAMPLES
The following will resample input.wav to 44.1kHz and save the output to
out.wav:
.Bd -literal -offset indent
$ bi input.wav 44100 output.wav
.Ed
.Sh AUTHORS
The
.Nm
tool was written by
.An Matt Jibson Aq matt.jibson@gmail.com ,
based on work done by Juluis O. Smith III:
http://www-ccrma.stanford.edu/~jos/resample/.
